### ISSUE TITLE
atlas about Neurite OASIS Sample Data

### ISSUE THREAD

**Issue by DopamineLcy** [adalca/medical-datasets#11]
Thank you for your remarkable "VoxelMorph" series work!
I'd like to use Neurite OASIS Sample Data to do registration research, but how can I get atlas and corresponding segmentation of this dataset.

Best wishes.

**Comment by DopamineLcy** [comment]
Or is it reasonable to use the "atlas.npz" file in voxelmorph repository directly?

**Comment by adalca** [comment]
@DopamineLcy thanks for your comments! Yes, atlas.npz in voxelmorph will work with that `aligned_*.nii.gz` files:

![image](https://user-images.githubusercontent.com/3219675/120804235-6c2e7800-c512-11eb-8cb4-b10929ac6090.png)

**Comment by DopamineLcy** [comment]
@adalca Thank you for your reply, which helps a lot!
Maybe I need more data for the research, only this dataset may be not enough. But I found that doing segmentation with softwares like FreeSurfer is very time-consuming. Is there any dataset preprocessed and segmented like this one? Or is there any method to preprocess the data such as ABIDE or ADNI to be like this dataset rapidly. Thanks you.

**Comment by adalca** [comment]
@DopamineLcy I'm not aware of other large datasets that are this well processed, except maybe(?) mindboggle-101, although I haven't used it myself. We hope to release a DL processing tool to go from arbitrary image to this quality of segmentation.

**Comment by DopamineLcy** [comment]
@adalca Thank you very much!
